config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :reviews
  end

  resources :businesses do
    resources :reviews
    post 'like',   to: 'socializations#like'
    post 'unlike', to: 'socializations#unlike'
  end

  authenticated :user do
    root 'businesses#index', as: 'authenticated_root'
  end

  root 'businesses#index'

end

app/models/business.rb
class Business < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true
  acts_as_followable
  acts_as_likeable
  geocoded_by :full_street_address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def full_street_address
    "#{self.address} #{self.city}, #{self.state}"
  end

end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :users
  belongs_to :business, dependent: :destroy
  validates :title, :rating, :description, presence: true
  validates :user_id, uniqueness: {scope: :business_id, message: "May not leave more than one review.  Please edit or delete prior review"}
  acts_as_likeable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:twitter]

  has_many :reviews, dependent: :destroy
  acts_as_follower
  acts_as_liker
  acts_as_likeable

  # for paperclip gem to add avatars for each user
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.from_omniauth(auth)
    # binding.pry
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.name + '@local.com'
      user.password = Devise.friendly_token[0,20]
      user.given_name = auth.info.name
      # user.family_name = auth.info.name.split(' ').last   # assuming the user model has a name
      # user.avatar = auth.info.image
    end
  end

  def self.new_with_session(params, session)
      super.tap do |user|
        data = session["devise.twitter_data"]
          user.avatar = data["image"] if user.avatar.blank?
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :user_status
  
  def user_status
    @user_status = if user_signed_in?
                      true
                    else
                      false
                    end
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]


  def index
    @businesses = Business.all
    respond_to do |format|
      format.html
      format.json { render json: @businesses }
    end

  end

  def show
    @business = Business.find(params[:id])
    @reviews = @business.reviews.all

    respond_to do |format|
      format.html
      # format.json { render json: @business }
      format.js
    end

  end

  def create
    @business = Business.new(business_params)
    @business.save
    redirect_to @business
  end

  def new
    @business = Business.new
  end

  def edit
    @business = Business.find(params[:id])
  end

  def update
    @business = Business.find(params[:id])
    if @business.update_attributes(business_params)
      redirect_to @business
    else
      render 'edit'
    end
  end

  def destroy
    @business = Business.find(params[:id])
    @business.destroy
    redirect_to businesses_path
  end

  private

  def business_params
    params.require(:business).permit(:address, :name, :city, :state, :description)
  end
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  def edit
  end

  def new
  end

  def update
  end

  def destroy
  end

  def show
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def edit
    @business = Business.find(params[:business_id])
    @review = @business.reviews.find(params[:id])
  end

  def create
    @business = Business.find(params[:business_id])
    @review = @business.reviews.new(params.require(:review).permit(:title, :description, :rating))
    @review.user_id = current_user.id
    if @review.save
      redirect_to @business
    else
      render 'new'
    end
  end

  def new
    @business = Business.find(params[:business_id])
    @review = @business.reviews.new
  end

  def update
    @business = Business.find(params[:business_id])
    @review = @business.reviews.find(params[:id])
    if @review.update_attributes(params.require(:review).permit(:title, :description, :rating))
      redirect_to @business
    else
      render 'new'
    end
  end

  def destroy
    @business = Business.find(params[:business_id])
    @review = @business.reviews.find(params[:id])
    @review.destroy
    redirect_to @business
  end

  def show
  end
end

app/controllers/socializations_controller.rb
class SocializationsController < ApplicationController
  before_filter :load_socializable

  def like
    current_user.like!(@socializable)
    respond_to do |format|
      format.html
      format.js
    end

  end

  def unlike
    current_user.unlike!(@socializable)
    respond_to do |format|
      format.html
      format.js
    end
  end

private
  def load_socializable
    @business = Business.find(params[:business_id])
    @socializable =
      case
      when id = params[:review_id] # Must be before :item_id, since it's nested under it.
        @business.reviews.find(id)
      when id = params[:business_id]
        Business.find(id)
      when id = params[:user_id]
        User.find(id)
      else
        raise ArgumentError, "Unsupported socializable model, params: " +
                             params.keys.inspect
      end
    raise ActiveRecord::RecordNotFound unless @socializable
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      # raise omni = request.env["omniauth.auth"].to_yaml
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => "twitter") if is_navigational_format?
      else
        session["devise.twitter_data"] = request.env["omniauth.auth"].except(:extra)
        redirect_to new_user_registration_url
      end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.all
  end

  private

  def user_params
    params.require(:user).permit(:family_name, :given_name, :status, :city, :state, :email, :username, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # @business_by_state = Business.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/business/edit.html.erb
<h1>Business#edit</h1>
<p>Find me in app/views/business/edit.html.erb</p>

app/views/business/new.html.erb
<h1>Business#new</h1>
<p>Find me in app/views/business/new.html.erb</p>

app/views/businesses/_form.erb
<% if @business.errors.full_messages.any? %>
    <% @business.errors.full_messages.each do |error_message| %>
        <%= error_message if @business.errors.full_messages.first == error_message %> <br />
    <% end %>
<% end %>

<%= form_for @business do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :state %>
    <%= f.text_field :state %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.submit 'Submit' %>

<% end %>

app/views/businesses/edit.html.erb
<h1>Business#edit</h1>
<p>Find me in app/views/business/edit.html.erb</p>
<%= render 'form' %>

app/views/businesses/index.html.erb
<div class="jumbotron text-center">
  <div style='width: 100%;'>
    <div id="geolocation" style='width: 100%; height: 400px;'></div>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <% @businesses.limit(10).each do |b| %>
        <h4><%= link_to b.name, business_path(b) %></h4>
        <p><%= b.description %></p>
    <% end %>

  </div>

  <div class="col-lg-6">
    <% @businesses.limit(5).each do |b| %>
        <h4><%= link_to b.name, business_path(b) %></h4>
        <p><%= b.description %></p>
    <% end %>

  </div>
</div>
<hr>

<div class="jumbotron text-center">
  <h2>Moving from Bootstrap 2.x to 3.0?</h2>
  <p class="lead">Everything has changed, so you can't just replace the 2.x with the 3.0 files. The folks at Bootply, the Bootstrap Playground have created a migration guide to help.</p>
  <p><a class="btn btn-large btn-success" href="http://www.bootply.com/bootstrap-3-migration-guide" target="ext">Migration Guide</a></p>
</div>

app/views/businesses/new.html.erb
<h1>Business#new</h1>
<p>Find me in app/views/business/new.html.erb</p>

<%= render 'form' %>

app/views/businesses/show.html.erb
<h1> <%= @business.name %> </h1>
<p> <%= @business.address %></p>
<p> <%= @business.city %></p>
<p> <%= @business.state %></p>
<p> <%= @business.description %></p>
<p> <%= link_to 'Edit this business', edit_business_path %></p>

<p>Total Reviews: <%= @reviews.count %></p>
<%= link_to 'Add a review', new_business_review_path(@business) %>
<% if @user_status %>
  <div class="social">
    <% if current_user.likes?(@business) %>
      <%= button_to "Unlike", business_unlike_path(@business), remote: :true, method: :post, class: "social-like" %>
    <% else %>
      <%= button_to "Like", business_like_path(@business), remote: :true, method: :post, class: "social-unlike" %>
    <% end %>
  </div>
<% end %>

<p class="likes-count">
  <%= pluralize(@business.likers(User).count, 'Like') %>
</p>



        <div class="row">
          <div class="col-md-8">
            <h2 class="page-header">Comments</h2>
            <section class="comment-list">

              <% @reviews.each do |r| %>
                  <% u = User.find(r.user_id) %>

              <!-- First Comment -->
              <article class="row">
                <div class="col-md-2 col-sm-2 hidden-xs">
                  <figure class="thumbnail">
                    <%= image_tag u.avatar.url(:thumb), class: "img-responsive" %>
                    <figcaption class="text-center"><%= link_to u.given_name, user_path(u.id) %></figcaption>
                  </figure>
                </div>
                <div class="col-md-10 col-sm-10">
                  <div class="panel panel-default arrow left">
                    <div class="panel-body">
                      <header class="text-left">
                        <div class="comment-user"><i class="fa fa-user"></i> <%= r.title %></div>
                        <time class="comment-date" datetime="<%= r.created_at %>"><i class="fa fa-clock-o"></i> Commented <%= time_ago_in_words(r.created_at) %> ago.</time>
                      </header>
                      <div class="comment-post">
                        <p>
                         <%= r.description %>
                        </p>
                      </div>
                      <% if @user_status %>
                          <% if current_user.id == u.id %>
                              <p class="text-right"><i class="fa fa-reply"></i><%= link_to 'Edit', edit_business_review_path(@business.id, r.id),class: "btn btn-default btn-sm" %>
                              <%= link_to '[X]', business_review_path(@business.id, r.id), method: :delete %></p>
                          <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </article>
              <% end %>
            </section>
          </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script type="javascript">
    userName = <%= current_user %>;
  </script>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="navbar navbar-inverse">
  <div class="container">
    <a class="navbar-brand" href="#">Brand</a>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Businesses', businesses_path %></li>
        <% if !user_signed_in? %>
            <li><%= link_to 'Log-In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up',  new_user_registration_path%></li>
        <% else %>
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <% end %>
    </ul>
  </div>
</div>

<div class="container">

  <%= yield %>

</div> <!-- /container -->




</body>
</html>

app/views/reviews/_form.erb
<% if @review.errors.full_messages.any? %>
    <% @review.errors.full_messages.each do |error_message| %>
        <%= error_message if @review.errors.full_messages.first == error_message %> <br />
    <% end %>
<% end %>

<%= form_for [@business, @review] do |f| %>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.label :rating %>
      <%= f.number_field :rating, in: 1..5 %>
    </p>

    <%= f.submit 'Submit' %>

<% end %>

app/views/reviews/destroy.html.erb
<h1>Review#destroy</h1>
<p>Find me in app/views/review/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Review#edit</h1>
<p>Find me in app/views/review/edit.html.erb</p>
<%= render 'form' %>

app/views/reviews/new.html.erb
<h1>Review#new</h1>
<p>Find me in app/views/review/new.html.erb</p>
<%= render 'form' %>

app/views/reviews/show.html.erb
<h1>Review#show</h1>
<p>Find me in app/views/review/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Review#update</h1>
<p>Find me in app/views/review/update.html.erb</p>

app/views/socializations/like.js.erb
$('.likes-count').text("<%= j pluralize(@business.likers(User).count, 'Likes') %>");
$('.social').html('<%= j button_to "Unlike", business_unlike_path(@business), remote: :true, method: :post, class: "social-unlike" %>');

app/views/socializations/unlike.js.erb
$('.likes-count').text("<%= j pluralize(@business.likers(User).count, 'Likes') %>");
$('.social').html('<%= j button_to "Like", business_like_path(@business), remote: :true, method: :post, class: "social-unlike" %>');

app/views/users/_form.erb
<%= form_for @user do |f| %>
<p>
  <%= f.label :given_name %>
  <%= f.text_field :given_name %>
</p>
<p>
  <%= f.label :family_name %>
  <%= f.text_field :family_name %>
</p>

<p>
  <%= f.label :city %>
  <%= f.text_field :city %>
</p>
<p>
  <%= f.label :state %>
  <%= f.text_field :state %>
</p>

<p>
  <%= f.label :avatar %>
  <%= f.file_field :avatar %>
</p>

    <%= f.submit 'Submit' %>

<% end %>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Profile</h1>

<div class="row">
  <div class="col-sm-2 col-md-2">
    <%= image_tag @user.avatar.url(:medium), class: "img-responsive" %>
  </div>
  <div class="col-sm-4 col-md-4">
    <blockquote>
      <p><%= @user.given_name %> <%= @user.family_name %></p> <small><cite title="Source Title"><%= @user.city %>, <%= @user.state %>  <i class="glyphicon glyphicon-map-marker"></i></cite></small>
    </blockquote>
    <p> <i class="glyphicon glyphicon-envelope"></i> <%= @user.email %>
      <br
      /> <i class="glyphicon glyphicon-globe"></i>
      <br /> <i class="glyphicon glyphicon-gift"></i> <%= @user.created_at %></p>
  </div>
</div>

<% if @user_status && @user.id == current_user.id %>
<p>New Status:</p>
  <%= form_for @user, url: user_path(@user), method: :patch do |f| %>
      <%= f.text_field :status %>
      <%= f.submit 'Update Status'%>
    <% end %>
    <p><%= link_to 'Edit Profile', edit_user_path(@user) %></p>
<% end %>


<div class="row">
  <div class="col-md-8">
    <h2 class="page-header">Recent Reviews:</h2>
    <section class="comment-list">

      <% @reviews.each do |r| %>
          <% b = Business.find(r.business_id) %>
          <!-- First Comment -->
          <article class="row">
            <div class="col-md-2 col-sm-2 hidden-xs">
              <figure class="thumbnail">
                <%= image_tag @user.avatar.url(:thumb), class: "img-responsive" %>
                    <figcaption class="text-center"><%= link_to b.name, business_path(b.id) %></figcaption>
                    </figure>
                    </div>
                    <div class="col-md-10 col-sm-10">
                      <div class="panel panel-default arrow left">
                        <div class="panel-body">
                          <header class="text-left">
                            <div class="comment-user"><i class="fa fa-user"></i> <%= r.title %></div>
                            <time class="comment-date" datetime="<%= r.created_at %>"><i class="fa fa-clock-o"></i> Commented <%= time_ago_in_words(r.created_at) %> ago.</time>
                          </header>
                          <div class="comment-post">
                            <p>
                              <%= r.description %>
                            </p>
                          </div>
                          <% if @user_status %>
                              <% if current_user.id == u.id %>
                                  <p class="text-right"><i class="fa fa-reply"></i><%= link_to 'Edit', edit_business_review_path(@business.id, r.id),class: "btn btn-default btn-sm" %>
                                        <%= link_to '[X]', business_review_path(@business.id, r.id), method: :delete %></p>
                                    <% end %>
                              <% end %>
                              </div>
                              </div>
                              </div>
                              </article>
                          <% end %>
                          </section>
                          </div>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Fixed Width Layout</h1>
  <p class="lead">The Bootstrap 3 grid is fluid only. This example shows how to use a custom container to create a fixed width layout.</p>
  <p><a class="btn btn-large btn-success" href="http://bootply.com/tagged/bootstrap-3" target="ext">More Examples</a></p>
</div>

<div class="row">
  <div class="col-lg-6">
    <h4>Mobile First</h4>
    <p>Responsive by default, and a clean "flat" design.</p>

    <h4>Powerful Grid</h4>
    <p>3 responsive grid sizes to control the grid layout on tiny, small and large displays.</p>
  </div>

  <div class="col-lg-6">
    <h4>New Elements</h4>
    <p>New panels, list groups, glyphicons and justified navigation.</p>

    <h4>Less Bloat</h4>
    <p>The optimized CSS is in a single file. Glyphicons are now separate.</p>
  </div>
</div>

<hr>

<div class="jumbotron text-center">
  <h2>Moving from Bootstrap 2.x to 3.0?</h2>
  <p class="lead">Everything has changed, so you can't just replace the 2.x with the 3.0 files. The folks at Bootply, the Bootstrap Playground have created a migration guide to help.</p>
  <p><a class="btn btn-large btn-success" href="http://www.bootply.com/bootstrap-3-migration-guide" target="ext">Migration Guide</a></p>
</div>